---
title: "05-Introduction to Quantum Physics"
author:
  - name: Physics Theory II PHYS2001
    orcid: 0000-0001-9813-9323
    email: eugene.hickey@tudublin.ie
    affiliation: 
      - name: Technological University Dublin
        url: www.tudublin.ie
format:
  revealjs:
    slide-number: true
    show-slide-number: all
logo: logo.jpg
include-in-header:
  - text: |
      <link rel = "shortcut icon" href = "logo.jpg" />
css: logo.css
footer: "Physics - Quantum"
editor: visual
---

## Summary

In solid form, many molecules line up in regular arrays showing long range order. These are crystals. Classically these are distinguished by flat faces and sharp edges, but in reality most solids are crystalline, just that the individual crystals are so small we don't recognise this.

The experimental study of crystals is a powerful way to unpick the structure of the molecules from which they are composed.

## Contents

::: {style="font-size: 80%;"}
1.  Nature of Light
2.  Blackbody Radiation & Planck
3.  Photoelectric Effect
4.  Energy & Momentum of Photons
5.  Compton Effect
:::

## Wave Nature of Light

::: {style="font-size: 70%;"}
- optical interference patterns explained by waves

:::

## Particle Nature of Light

::: {style="font-size: 70%;"}
- photoelectric effect
- pair-production

:::

## Blackbody Radiation

::: {style="font-size: 70%;"}
- every object emits light because of its temperature
    - hot bodies are brighter
    - hot bodies $\implies$ more intense colours
        - $infrared \rightarrow  crimson \rightarrow yellow \rightarrow blue \rightarrow uv$
    - spectrum explained by Planck's Radiation Law
    
${\displaystyle B_{\nu }(\nu ,T)={\frac {2h\nu ^{3}}{c^{2}}}{\frac {1}{e^{h\nu /(k_{\mathrm {B} }T)}-1}}}$

- introduces Plank's constant, $h = 6.626 \times 10^{-34} Js$
- also $\hbar = \frac{h}{2\pi} = 1.055 \times 10^{-34} Js$
:::

## 


## References

-   [Young & Freedman - chapter 42.3](https://ebookcentral.proquest.com/lib/tudublin/reader.action?docID=5853694&ppg=1445){target="_blank"}
