---
title: "07-Shrodinger Equation - Particle in a Box"
author:
  - name: Physics Theory II PHYS2001
    orcid: 0000-0001-9813-9323
    email: eugene.hickey@tudublin.ie
    affiliation: 
      - name: Technological University Dublin
        url: www.tudublin.ie
format:
  revealjs:
    slide-number: true
    show-slide-number: all
    chalkboard: true
logo: logo.jpg
include-in-header:
  - text: |
      <link rel = "shortcut icon" href = "logo.jpg" />
css: logo.css
footer: "Physics - Quantum"
editor: visual
---

## Summary

In our first application of the Schrödinger Equation, we'll look at a particle in a 1 -dimensional box. This particle is at zero potential in the interval $0 \leq x \leq a$ but cannot move outside these bounds.


## Contents

:::::::: columns
:::: {.column width="40%"}
::: {style="font-size: 90%;"}
1.  Wave Nature of Light
2.  Particle Nature of Light
    1.  Blackbody Radiation & Planck
    2.  Photoelectric Effect
        -   Energy & Momentum of Photons
    3.  Compton Effect
    4.  Pair Production
:::
::::

::: {.column width="10%"}
:::

:::: {.column width="40%"}
::: {style="font-size: 90%;"}
3.  Mathematics of Wave Packets
4.  Uncertainty Principle
5.  Wave Nature of Particles
6.  Equations
7.  References
:::
::::
::::::::

## Time Dependent Schrödinger Equation

::: {style="font-size: 90%;"}

- finished last week with the Time Dependent Schrödinger Equation

<center> $i \hbar \frac{\partial \Psi}{\partial t} = - \frac{\hbar^2}{2m} \frac{\partial ^2 \Psi}{\partial x^2} + V\Psi$ </center>

-  Lots of times the potential, V, doesn’t depend on time, just position.

- There’s a neat trick called separation of variables we can
use now.

<center> $\Psi (x, t) = \psi (x) T(t)$ </center>

:::
    
##

- Get:

<center> $i \hbar \frac{1}{T} \frac{\partial T}{\partial t} = - \frac{1}{\psi} \frac{\hbar^2}{2m} \frac{\partial ^2 \Psi}{\partial x^2} + V(x)$ </center>

<br>

- Left hand side just depends on time, right hand side just on x

$\implies$ both sides must be equal to some constant, call it E say

$\implies$ got ourselves two equations here

## Time Dependence

- Working with the left (time) side of the equation gives us:

<center> $i \hbar \frac{\partial T}{\partial t} = E \times T(t)$ </center>

- Solutions to this are fairly straightforward and not that interesting

<center> $T(t) = A e^{-iEt/\hbar}$ </center>

- Gives temporal oscillations of the wavefunction

## Time Independent Schrödinger Equation

- On the other hand, the spatial element is rich in solutions, depends on shape of V(x)

- Get

<center> $- \frac{\hbar^2}{2m} \frac{\partial ^2 \psi}{\partial x^2} + V(x) \psi = E \psi$ </center>

- This is the time independent Schrödinger Equation

- Turns out, when we compare to the free space version, that E is the total energy of the system.

## Boundary Conditions

::: {style="font-size: 75%;"}

* Solving problems using Time independent Schrödinger Equation means

    + Applying different natures of the potential, V
    
    + But also using boundary conditions, constraints on the wavefunction that tell us about the possible solutions
    
        - Wavefunction must be a continuous single valued function of position and time
        
        - The integral of the squared value of the wavefunction over all values of x must be finite (normalisable) 
        
        - The first derivatives of the wavefunction in x must be continuous everywhere except when there is an infinite discontinuity in the potential
        
- We'll first look at the nature of solutions to Schrödinger's Equation, and then tackle some examples and put Schrödinger to work

:::

## Solutions of Schrödinger's Equation

::: {style="font-size: 90%;"}

* Equation is linear in $\psi$

    + Superposition principle, if $\psi_1$ and $\psi_2$ are solutions then so is $\psi_1 + \psi_2$

        - and indeed $A\psi_1 + B\psi_2$

* Solution solved by eigenfunctions, $\psi_n$, and corresponding eigenvalues, $E_n$

* Set of all solutions forms an orthogonal basis set

    + $\int \psi_n \psi_m dx = 0 \;if \; n \neq m$

    + Can make up any function from linear combination of $\psi$'s

        - $F(x) = \Sigma \psi_n$

:::
        
## Examples of Time Independent Schrödinger Equation

- Infinite square well

- Finite square well

- Harmonic oscillator

- All of these are 1-D

- We'll advance to 3-D later

    – Hydrogen atom
    
    – etc



## Equations

::::: columns
::: {.column width="50%"}
-   $A = A_0 sin(kx - \omega t)$
-   $A = e^{i(kx - \omega t)}$)
-   $\frac{\partial^2A}{\partial x^2}-(\frac{k}{\omega})^2 \frac{\partial^2A}{\partial x^2} = 0$
-   $\omega = 2 \pi f$
-   $k = \frac{2 \pi}{\lambda}$
:::

::: {.columns width="\"50%"}
-   $v = \frac{\omega}{k}$
-   \$p = \frac{h}{\lambda} = \hbar k \$
-   $E = hf = \frac{hc}{\lambda}= \hbar c k$
-   $v_p = \omega / k$
-   $v_g = \partial \omega / \partial k$
-   $\Delta \lambda = \frac{h}{mc} (1 - cos \theta)$
:::
:::::

## References

-   [Young & Freedman - chapter 42.3](https://ebookcentral.proquest.com/lib/tudublin/reader.action?docID=5853694&ppg=1445){target="_blank"}
