---
format: 
  revealjs:
    theme: [default, style.scss]
    width: 1600
    height: 900
    footer: '<a href="https://www.fizzics.ie/">fizzics.ie</a>'
tab-border-collapse: collapse
background-size: 50% 50%;
include-in-header:
  - text: |
      <link rel = "shortcut icon" href = "img/bullfinch.jpg" />
---
#  {.title}

::: r-fit-text
Eugene Hickey

[TU Dublin - Tallaght Campus]{.flow}
:::

::: footer
:::

---

:::: {.columns}
::: {.column width="25%"}


:::

::: {.column width="50%"}

### Research {.textcenter}


|                                 |                   |
|---------------------------------|-------------------|
| {{< li yrixyrst >}}    | Health Provision  |
| {{< li clcopglh >}} | Astrophysics      |
| {{< li wlpxtupd >}}         | Neuroscience      |
| {{< lif img/wired-lineal-1331-repository.json >}}              | R package (genes) |


: {tbl-colwidths="[15,85]"}

:::
::: {.column width="25%"}


:::
::::

---

## PhD Students

<br>


:::: {.columns}
::: {.column width="50%"}

### Andrea Heaney {.textcenter}

- 2<sup>nd</sup> year
- gender bias in health care
- examining clinical use of AI 


:::

::: {.column width="50%"}

### Oisin Creaner {.textcenter}

- finished 2017
- postdocs in DIAS and Berkeley (NESC)
- now in DCU    
- time-domain astronomy
- correct for atmospheric effects


:::
::::


<br>
- also two masters by research students (Elena & Tom)


---

## Collaborations
<br>

:::: {.columns}
::: {.column width="50%"}

### External {.textcenter}


|                                  |        |
|----------------------------------|--------|
| {{< fa solid magnifying-glass-chart >}}  | ML-Labs (TUD, UCD, DCU)  |
| {{< fa solid people-roof >}}  | NORF (citizen astro)  |
| {{< fa solid graduation-cap >}}   | EUT+ (data science)  |
| {{< fa solid satellite >}}           | COST Action GAIA   |
| {{< fa solid staff-snake >}}            | NHSr (workshops/conferences)  |
| {{< fa solid globe >}}     | IRGEOS (C-SPAN)|
| {{< fa solid server >}}     | ICHEC |

: {tbl-colwidths="[15,85]"}

:::

::: {.column width="50%"}

### Internal {.textcenter}


|                                     |                             |
|-------------------------------------|-----------------------------|
| {{< fa solid building-columns >}}   | University Rankings Group   |
| {{< fa solid laptop-code >}}        | Student Digital Experience  |
| {{< fa regular calendar-check >}}   | Timetables                  |
| {{< fa solid chalkboard-user >}}    | Learning Management Systems |


: {tbl-colwidths="[15,85]"}

:::
::::

---


:::: columns
::: {.column width="60%"}
::: r-fit-text
Thank you!

|                                 |                   |
|---------------------------------|-------------------|
| {{< fa solid blog >}}    | [www.fizzics.ie/](https://www.fizzics.ie/)  |
| {{< fa brands orcid >}} | [0000-0001-9813-9323](https://orcid.org/my-orcid?orcid=0000-0001-9813-9323)|
| {{< fa brands mastodon >}}|[\@eugene100hickey](https://mastodon.social/@eugene100hickey)|
| {{< fa brands twitter >}} | [\@eugene100hickey](https://twitter.com/eugene100hickey)|
| {{< fa brands github >}}| [eugene100hickey.github.io/](https://github.com/eugene100hickey)|

   
:::
:::

::: {.column width="40%"}
::: {#fig-website}

<iframe onload="this.width=screen.width;this.height=screen.height*0.90;" src="https://www.fizzics.ie/teaching.html"></iframe>
website / blog
:::

:::
:::
