---
title: "03 - Nuclear Energy"
author:
  - name: Nuclear Physics PHYS2829
    orcid: 0000-0001-9813-9323
    email: eugene.hickey@tudublin.ie
    affiliation: 
      - name: Technological University Dublin
        url: www.tudublin.ie
format:
  revealjs:
    slide-number: true
    show-slide-number: all
logo: logo.jpg
include-in-header:
  - text: |
      <link rel = "shortcut icon" href = "logo.jpg" />
css: logo.css
footer: "Nuclear Physics"
editor: visual
---

## Summary

<br>

::: {style="font-size: 90%;"}
The strength of the nuclear force leads to enormous energies. These can be released when there is a change in nuclear profile. In the last section, we saw $¥alpha$, $¥beta$, and $¥gamma$ radiations with energies of the order of 1MeV. Energies of around 200MeV can be released when a heavy nucleus splits (**fission**), and ten times more when light nuclei combine (**fusion**).

In this section, we'll look at the physical sources of these energies, specific examples of nucleear reactions involving them, and the uses they have been put to.
:::

## Contents

1.  Nuclear Fission
2.  Nuclear Fusion

## Nuclear Fission

-   During Fission, a heavy isotope splits into two or more fragments, binding energy is released during the process. Nuclear reactors and Atomic bombs make use of this. A typical reaction is $^1n¥; +¥; ^{235}U ¥rightarrow ¥;^{236}U ¥rightarrow ¥;^{141}Ba +¥; ^{92}Kr +  3 ^1n$

-   Approximately 200 MeV of energy is released per fission

    -   B/A for $^{235}U$ = 7.59MeV, for $^{141}Ba$ = 8.8MeV, for $^{92}Kr$ = 7.83MeV

## Reason for Nuclear Fission

::: {style="font-size: 90%;"}
-   Coulomb repulsion is at the heart of nuclear fission

    -   remember, the binding energy per nucleon curve only dips down, giving a maximum around $^{56}Fe$, when we introduce the Coulomb repulsion term

    -   a large nucleus can deform, no longer spherical. The increase in surface energy being offset by a larger distance between protons

    -   consider the reaction above. If the $^{141}Ba$ and $^{92}Kr$ nuclei are just touching, their separation will be $1.2 ¥times ¥sqrt[3]{141} + 1.2 ¥times ¥sqrt[3]{92} = 11.66nm$

    -   the potential energy will be given by $E = ¥frac{1}{4¥pi¥epsilon_0} ¥frac{q_1q_2}{r} ¥approx 250MeV$ where the charge on $^{141}Ba$ is $56 ¥times e$ and on $^{92}Kr$ is $36 ¥times e$
:::

## Spontaneous Fission

-   spontaneous fission is rare, all but the heaviest nuclei (but, all the really heavy nuclei) will decay by $¥alpha$ particle emission with much higher probability

    -   anything with A > 300 will do this straight away

-   examples include $^{238}U$, $^{240}Pu$, $^{252}Cf$

-   the heavy nuclei will split into two daughter nuclei

    -   $^{252}Cf ¥rightarrow ^{140}Cs + ^{109}Tc + 3 ^1n$

    -   one daughter nucleus significantly heavier than the other

    -   also, a batch of neutrons emitted

## Stimulated Fission

-   rather than waiting around for spontaneous fission, we can prompt it to happen by bambarding a heavy nucleus with neutrons

    -   $^{235}U  + ^1n ¥rightarrow ^{236}U$

    -   $^{236}U$ is even-even and more stable than $^{235}U$

    -   adding this neutron leads to a $^{236}U$ having extra energy

    -   B/A for $^{235}U$ is 7.590907 MeV/nucleon, for $^{236}U$ it's 7.586477 MeV/nucleon

        -   gives 6.54 MeV after absorbing neutron

        -   enough to quantum tunnel through fission barrier

## 

-   case for stimulated emission from $^{238}U$ more complicated

    -   again, looking to do this by absorbing a neutron

    -   $^{238}U$ is already even-even, $^{239}U$ is even-odd

        -   B/A for $^{238}U$ is 7.570120 MeV/nucleon, for $^{239}U$ 7.558557 MeV/nucleon

        -   only get 4.81 MeV by absorbing neutron

        -   not close enough to potential barrier to tunnel

        -   absorbed neutron needs to arrive with ‾1MeV extra energy

## Absorbing Neutrons

-   slow neutrons (called thermal) much more easily absorbed

    - 584 barns at room temperature ($¥frac{1}{40}eV$)
    
    - 1 barn at 1MeV
    
- means that fissioning $^{238}U$ (or $^{242}Pu$) is much more difficult than fissioning $^{235}U$ (or $^{239}Pu$).

## Emitting Neutrons

::: {style="font-size: 80%;"}

- this will be crucial

    - difference between making a power plant or making a bomb
    
-   During fission several neutrons are emitted by each nucleus and these cause further fission

    - can cause a chain reaction

        - these are called **Prompt** neutrons
        
        - appear within $10^{-12}s$ of fission
    
    
    -   reason for neutron emmission is to maintain proton/neutron ratio appropriate for atomic mass
    
    -   fission products tend to be $¥beta$ emitters
    
        - a small (‾ 1%) but important number of these will emit neutrons 
        
        - these are called **Delayed** neutrons
        
        - couldn't regulate a power plant without them
        
:::
    
##
    
-   number of neutrons (*k*) that propagate reaction is crucial
    -   if k ¥< 1 then reaction dies out
    -   if k ¥> 1 then explosion
    -   if k $¥approx$ 1 then controlled power plant

## Controlled Fission Power

::: {style="font-size: 85%;"}

- natural uranium is 99.28% $^{238}U$, only 0.72% $^{235}U$

- usually need to enrich it to ‾3% $^{235}U$

- for $^{235}U$ typically get 2.5 neutrons per fission

    - but these are *hot* neutrons, not easily absorbed
    
       - need to slow them down
       
       -   slow down by collisions with light nuclei
    
       -   ***moderator***, usually water (contains $^1H^+$) or heavy water (with deuterium) or graphite carbon

-   control rods made from **Cadmium** can be used to absorb neutrons, keep k close to 1

-   surface to volume ratio important

    -   critical mass (about 50kg for $^{235}U$)
    
:::

## Significant Fission Products

::: {style="font-size: 90%;"}

- fission produces two daughter nuclei, one heavy (A ‾ 140) and one lighter (A ‾ 95)

- the two daughter products after fission will be neutron rich

    - tend to decay by $¥beta$ emission

- let's look at these in four issues:

    1. lots, maybe 10%, of the total fission energy comes from these subsequent decays
    
    1. the longer lived ($t_{¥frac{1}{2}} ¥approx ¥; years$) fragments are hazardous waste
    
    1. can interfere detrimentally with fission process. $^{135}Xe$ is the poster-child here.
    
    1. some of them can be useful

:::

##


### 1/ $¥beta$ after heat energy

::: {style="font-size: 75%;"}

- remember, about 200MeV per fission

- this is followed by about 20MeV from $¥beta$ decays of fragments

- problem is that this mostly happens slowly, over hours or days

- when nuclear power plant is shut down (control rods fully inserted) and fission stopped, large amounts of energy is still being produced

- this is what happened in Fukishima in Japan in March 2011

    - large earthquake and so plant was immediately shut down
    
    - but then tsunami knocked out all the cooling generators
    
    - after heat evaporated:
    
        - all the cooling water
        
        - melted the uranium cores
        
        - produced $H_2$ gas
        
        - and all four reactor buildings exploded

:::

##

### 2/ Hazardous Waste

- most of the fission products have short (‾seconds) half lives

- but some not

    - $^{90}Sr$ with a half life of 28 years
    
    - $^{137}Cs$ also 28 years
    
    - $^{99}Tc$ with a half life of 210 thousand years
    
    - $^{129}I$ with a half life of 16 million years
    
- the strontium particularly worrisome as it is chemically similar to calcium


##

### 3/ Reactor Poisons

::: {style="font-size: 85%;"}

- ‾6.4% of $^{235}U$ fissions produce $^{135}I$

- $^{135}I$ decays over 6.7 hours into $^{135}Xe$

- $^{135}Xe$ has a freakishly large neutron absorbtion cross section and a half life of several hours

- means reactor can't be restarted for several hours after a shut-down

- $^{135}Xe$ will get burnt off during normal reactor operation

    - but if reactor is idling at low power, $^{135}Xe$ will build up
    
    - curtails reactor control
    
    - lead to Chernobyl tragedy

:::

##

### 4/ Useful Fission Products

- most notable are $^{131}I$ (8 days)and $^{132}I$ (2.3 hours)

    - iodine radiation used in the diagnosis and treatment of thyroid disorders
    
- $^{90}Sr$ (28.91 years) can be used as an energy source

    - $^{90}Sr$ emits $¥beta^-$ becoming $^{90}Y$ (64 hours) then becoming $^{90}Zr$ which is stable
    
    - very few $¥gamma$ rays emitted so not hard to shield all radiation
    
## Fission Reactors

-   natural Uranium is about 1% $^{235}U$ (mostly $^{238}U$)

-   reactor grade is about 20% $^{235}U$

-   weapons grade is about 85% $^{235}U$

-   $^{239}Pu$ also fissionable

##

### 4<sup>th</sup> Generation Reactors - SMR

-   small and modular can be transported by road

-   higher temperatures so more efficient

-   liquid salt coolant (Natrium type) can act as energy reservoir

-   continuous fuel feed so no need to shut down to service

-   $^{238}U$ act as neutron absorber to control reaction rates

-   build on sites of old coal plants

-   cost about 竄ｬ3B, take ¥‾ 10 years

-   typically 80-300MW per reactor
    
## Fission Bombs

::: {style="font-size: 80%;"}

- in contrast to nuclear reactors, in a bomb an uncontrolled fission chain reaction is needed

- want as many neutrons as possible, and has to happen fast

    - only *prompt* neutrons important here
    
- need to reduce neutron losses from the surface

    - pellet of $^{235}U$ needs to be big enough to reduce surface / volume ratio
    
    - typically 10kg minimum
    
- need high purity $^{235}U$ or $^{239}Pu$

- need to ensure the nuclei get a chance to fission before bomb blows itself apart

    - mean free path of fast neutrons in $^{235}U$ is about 10cm

:::

##

### Fission bomb types

::: {style="font-size: 80%;"}

- two solutions to that last problem:

    -   gun type - $^{235}U$ (*Little Boy* dropped on Hiroshima)
    
    -   implosion type - $^{239}Pu$ (*Fat Man* dropped on Nagasaki and *Trinity* test in Nevada)
    

- in the cases above, only a few percent of the fissile material actually fissioned

    - yield from explosion give by :
    
    $(number ¥; of ¥; fission ¥; events) ¥; = ¥; (mass ¥; of ¥; ^{235}U) ¥; ¥div ¥; 235.0439 ¥; ¥times 1.6605 ¥times 10^{-27} ¥; ¥times ¥; efficiency$
    
    $(yield ¥; in¥; joules) ¥; = ¥; (number ¥; of ¥; fission ¥; events) ¥; ¥times ¥; (200MeV) ¥; ¥div ¥; e$ Joules
    
    $(Yield ¥; in ¥; kilotons ¥; TNT) ¥; = ¥; (yield ¥; in¥; joules) ¥; ¥div ¥; 4.184 ¥times 10^{12}$ kilotons

:::

##

### Effect of Nuclear Bomb

- blast radius in km about cubed root of enegy in kilotons TNT

    - at this radius get pressure wave of 1/4 bar
    
    - debris at 200 km/hr
    
    - 3rd degree burns on exposed tissue
    
    - several Sv 
    
- ground burst explosions can sweep up debris combining them with fission productsand carry lethal doses of radiation for many tens of km

- air bursts can spread fission proucts over even larger areas


## Proton-Proton Cycle

$^1 H + ^1 H ¥rightarrow ^2 H + e^+ + ¥mu$

$^2 H + ^1 H ¥rightarrow ^3 He + ¥gamma$

$^3 He + ^3 He ¥rightarrow ^4 He + 2¥;^1 H+ + ¥gamma$

¥$N(t) = N_0;e¥^{-¥lambda t} ¥$

$t_{1/2} = ¥frac{log_e2}{¥lambda} = ¥frac{0.693}{¥lambda}$

$¥hbar = 1.0546 ¥times 10^{-34} Js$

## Fusion Reactors

-   use $^{3}T$ or $^{2}D$ (tritium or deuterium)

    -   $^{2}D$ naturally occuring (1 in 6,500 water molecules)

    -   $^{3}T$ is not, 12 year half-life

-   need temperatures of about 150 million $^{¥circ} C$

    -   laser induced fusion (pulse of 2 MJ)

    -   magnetic confinement (20T) in a **Tokamak** (doughnut shape)

-   Large science effort, current leaders are Lawrence Livermore in California (laser) and ITER in Cadarache in France (tokomak)

## Equations

## References {.smaller}

-   [Young & Freedman - chapter 43.2 (Nuclear Structure & Binding)](https://ebookcentral.proquest.com/lib/tudublin/reader.action?docID=5853694&ppg=1482){target="_blank"}

-   [Young & Freedman - chapter 43.6-8 (Reactions, Fission, & Fusion)](https://ebookcentral.proquest.com/lib/tudublin/reader.action?docID=5853694&ppg=1496){target="_blank"}

-   [Serway & Jewett - chapter 43.2 (Binding Energy)](https://viewer.ebscohost.com/EbscoViewerService/ebook?an=2639146&callbackUrl=https%3a%2f%2fresearch.ebsco.com&db=nlebk&format=EB&profId=ehost&lpid=&ppid=&lang=en&location=https%3a%2f%2fresearch.ebsco.com%2fc%2fsr37fs%2fsearch%2fdetails%2flh37eixz3f%3fdb%3dnlebk&isPLink=False&requestContext=&profileIdentifier=sr37fs&recordId=lh37eixz3f){target="_blank"}

-   [Serway & Jewett - chapter 43.3 (Nuclear Models)](https://viewer.ebscohost.com/EbscoViewerService/ebook?an=2639146&callbackUrl=https%3a%2f%2fresearch.ebsco.com&db=nlebk&format=EB&profId=ehost&lpid=&ppid=&lang=en&location=https%3a%2f%2fresearch.ebsco.com%2fc%2fsr37fs%2fsearch%2fdetails%2flh37eixz3f%3fdb%3dnlebk&isPLink=False&requestContext=&profileIdentifier=sr37fs&recordId=lh37eixz3f){target="_blank"}

-   [Serway & Jewett - chapter 43.7-10 (Reaction, Fission, & Fusion)](-%20%5BSerway%20&%20Jewett%20-%20chapter%2043.3%20(Nuclear%20Models)%5D(https://viewer.ebscohost.com/EbscoViewerService/ebook?an=2639146&callbackUrl=https%3a%2f%2fresearch.ebsco.com&db=nlebk&format=EB&profId=ehost&lpid=&ppid=&lang=en&location=https%3a%2f%2fresearch.ebsco.com%2fc%2fsr37fs%2fsearch%2fdetails%2flh37eixz3f%3fdb%3dnlebk&isPLink=False&requestContext=&profileIdentifier=sr37fs&recordId=lh37eixz3f)%7Btarget=%22_blank%22%7D){target="_blank"}

-   [4th Generation Fission Reactors](){target="_blank"}

-   [Nuclear Power from *Coursera*](https://www.coursera.org/learn/particle-physics/home/module/2){target="_blank"}

-   [nucleides](https://www.nndc.bnl.gov/nudat3/){target="_blank"}
